Fix SSRF vulnerability on blob
bluesky-social/atproto pull request #893
Opened 2023-04-25 12:05 UTC by yafesdot

**Description**

First of all, sorry in advance if this PR is a bit hilarious as this is one of my first contributions to any open-source project of this scale. SSRF potential may have seemed to me because I did not fully understand the protocol is also a possibility. However, if there is such vulnerability potential and more needs to be done to fix it than I have committed, please point it out in the comments, even if you are not a maintainer!

**Change(s) Made**

- Added URL validation to `getBlob()` function to prevent SSRF attacks.

**Related Issues**

None. Since I didn't come across any guidelines whatsoever I didn't open any on this topic either.

2023-04-25 18:55 UTC, pfrazee commented
Appreciate the PR. I suppose we have to look at this more closely.

Right now IIRC all blob URLs are being provided by your PDS and should be from their CDN, so it's assume they're trusted if they're handed to this API. (Correct me if I'm wrong dan or devin.) I'm unsure what kind of validation we could/would apply here that would secure this further.

2023-04-25 19:05 UTC, devinivy commented
I think some validation here is warranted, but I do need to take a closer look at it.  In this case we're hitting someone's PDS as described by their DID document, and the blob resolver shouldn't totally trust the DID document to point to a legitimate URL.  Will dig-in to this soon 👍

2023-04-27 18:57 UTC, yafesdot commented
Oopsie

2023-04-27 19:13 UTC, roj1512 commented
Don't mind it @yafesdot. You just pinged them.

2023-04-27 19:19 UTC, yafesdot commented
@roj1512 I *just* forgot that we can't just rename branches in git :woozy_face:, that's why...

2023-04-27 19:25 UTC, roj1512 commented
That was for good. Idk why they're not digging into it (and other PRs) anyway.

2023-05-02 01:45 UTC, dholms commented
We've just been horribly busy lately, getting through some PRs now. Thanks for your patience :)

2023-05-02 01:50 UTC, dholms requested changes
Okay this looks like a reasonable fix to me, but I think it would be better applied at the entry point for the untrusted address. 

Which is the `getPds` function in https://github.com/bluesky-social/atproto/blob/main/packages/did-resolver/src/atproto-data.ts

2023-05-02 14:24 UTC, yafesdot commented
Oh sorry, I just saw your review and requests. I'll make the changes you want!

2023-05-02 14:59 UTC, Matrix89 commented
@yafesdot Just a heads-up, when you discover an exploit, a security hole or anything that can be used by a malicious actor for an attack, please first look if the project has a disclosure program of some sort, before mentioning the issue in public

2023-05-02 15:02 UTC, yafesdot commented
> @yafesdot Just a heads-up, when you discover an exploit, a security hole or anything that can be used by a malicious actor for an attack, please first look if the project has a disclosure program of some sort, before mentioning the issue in public

I do when needed, but this one is not that much of a threatening one, so yeah.

2023-05-02 16:10 UTC, dholms commented
Yup yup this one was fine. Low attack vector & the vector is not even accessible in production deployments right now.

This did prompt me to draft a security readme for future vulnerability reports: https://github.com/bluesky-social/atproto/pull/954

Thanks again for the help! I'll keep an eye out for the changes

2023-05-02 16:19 UTC, yafesdot commented
@dholms it should work that way, but I'm unfortunately not that sure about that since I couldn't find a way to test it out directly.

2023-05-02 16:51 UTC, dholms approved these changes
yup looks good 👍

2023-05-02 16:51 UTC, merged